### ISSUE TITLE
Foreslåede rækkefølger for væremåder

### ISSUE THREAD

**Issue by sshine** [athas/EggsML#108]
Der er mange væremåder som fungerer bedre i bestemte rækkefølger. For eksempel, hvis concieggs er en "svensk gangsta", bliver det en sammenblanding af svensk og indskudt dansk gangsta. Eller hvis den er en "romersk unøjagtig", oversætter den tal til romertal hvorved unøjagtig mister noget af sin effekt.

Hvis der var en måde, man kunne foreslå rækkefølgen for afviklingen af væremåder, uden at man ødelægger muligheden for en uforudsigelig cocktail med mulige gentagelser af den samme væremåde, kunne en "svensk gangsta" betyde "gangsta svensk". Måske kunne `cmds/vær` tage imod et udråbstegn hvis man ikke ønsker at sortere væremåderne efter en anbefalet rækkefølge.

**Comment by Athas** [comment]
Kan det ikke manifesteres som en 'serveringsforslag'-kommando der kommer med forslag for en væremåde baseret på nogle regler?  F.eks:

```
<Athas> concieggs: serveringsforslag gangsta
<concieggs> Athas: 'pindofil gangsta' kan anbefales.
<Athas> concieggs: serveringsforslag feminazi
<concieggs> Athas: 'feminazi pindofil' er en yndet rækkefølge.
```

**Comment by sshine** [comment]
Jo, hvis vi har en række serveringsforslag, behøver de selvfølgelig ikke ændre på rækkefølgen automatisk. Man kunne også gøre den automatiske omrokering af væremåder optionel ved at slutte `cmds/vær` med '?'.

**Comment by Athas** [comment]
Ah, en slags omakase-udgave af `vær`, hvor man lader kokken om de nærmere detaljer?  Det er en god idé.

**Comment by martinmch** [comment]
<martinmch> concieggs: vær gangsta
<concieggs> martinmch: Jeg har snydt lidt.
