### ISSUE TITLE
Tillad polyglot eksekvering

### ISSUE THREAD

**Issue by sshine** [athas/EggsML#110]
Lige nu har vi `#!/usr/bin/env <fortolker>`.

Man burde have `#!/usr/bin/env polyglot php bash` som eksekverer med en tilfældig af `php` og `bash`.

Det må da være op til den enkelte programmør om programmet skal gøre det samme eller noget forskelligt afhængigt af hvilket sprog det bliver tolket som.

**Comment by svip** [comment]
Det er da lidt trist at `polyglot` kun kan tage `php` og `bash` som argumenter.

Og hvorfor er `ployglot` et argument på `env`?  Burde det ikke være sit eget program?

**Comment by sshine** [comment]
`php` og `bash` var eksempler. (Eftersom det er navne på fortolkere, burde det dog nok være `php-7.0`, da det er fortolkerens navn på serveren.)

`polyglot` bør være sit eget program ligesom `compile`, men ligesom

    #!/usr/bin/env compile

bør `polyglot` også kaldes som

    #!/usr/bin/env polyglot <sprog ...>

således at den kan ligge i `eggspi/polyglot` ligesom `eggspi/compile` og blive fundet uden eksakt sti.
