### ISSUE TITLE
Vejrudsigten viser sol om natten

### ISSUE THREAD

**Issue by Sword-Smith** [Athas/EggsML#112]
København er syd for polarcirklen!

**Comment by sshine** [comment]
21:33:46 <sword_smith> concieggs: vejrudsigt
    21:33:47 <concieggs> D. 17. kl. 22:  12° ☁           .=.,
    21:33:48 <concieggs> D. 18. midnat:  11° ☁          ;c =\
    21:33:48 <concieggs> D. 18. kl.  6:   9° ☀        __|  _/
    21:33:48 <concieggs> D. 18. kl. 12:  17° ☀      .'-'-._/-'-._
    21:33:48 <concieggs> D. 18. kl. 18:  19° ☀     /..   ____    \
    21:33:50 <concieggs> D. 19. midnat:  13° ☁    /' _  [<_->] )  \
    21:33:50 <concieggs> D. 19. kl.  6:   9° ☁   (  / \--\_>/-/'._ )
    21:33:50 <concieggs> D. 19. kl. 12:  15° ☁    \-;_/\__;__/ _/ _/
    21:33:52 <concieggs> D. 19. kl. 18:  17° ☁     '._}|==o==\{_\/
    21:33:52 <concieggs> D. 20. midnat:   7° 🌫      /  /-._.--\  \_
    21:33:52 <concieggs> D. 20. kl.  8:   7° ☁     // /   /|   \ \ \
    21:33:54 <concieggs> D. 20. kl. 14:  13° ☀    / | |   | \;  |  \ \
    21:33:54 <concieggs> D. 20. kl. 20:  15° ☀   / /  | :/   \: \   \_\
    21:33:54 <concieggs> D. 21. kl.  2:   9° ☀  /  |  /.'|   /: |    \ \
    21:33:56 <concieggs> D. 21. kl.  8:   9° ☀  |  |  |--| . |--|     \_\
    21:33:56 <concieggs> D. 21. kl. 14:  12° ☀  / _/   \ | : | /___--._) \
    21:33:56 <concieggs> D. 21. kl. 20:   9° ☀ |_(---'-| >-'-| |       '-'
    21:33:58 <concieggs> D. 22. kl.  2:   6° ☀        /_/     \_\

Jeg tror det skal tolkes som at der er skyfrit, men det er naturligvis ikke ensbetydende at solen er synlig.

Adfærden skyldes [denne linje](https://github.com/Athas/EggsML/blob/master/concieggs/cmds/vejrudsigt#L56) som ikke skelner mellem `sun`, `clear` og `fair`. Man kunne bruge et [månesymbol](https://unicode-search.net/unicode-namesearch.pl?term=MOON) afhængigt af tiden på døgnet - eggspi understøtter vist bare ikke solnedgang endnu.

**Comment by nqpz** [comment]
Desuden må nogen godt lave det så der kommer en tilfældig person ude på højre side.  Det er lidt trættende at se SUPERMAN *hver gang*.

**Comment by sshine** [comment]
Man kunne bruge Perl's [`DateTime::Event::Sunrise`](http://search.cpan.org/~jforget/DateTime-Event-Sunrise-0.0505/lib/DateTime/Event/Sunrise.pm).
