### ISSUE TITLE
Mangler pakker

### ISSUE THREAD

**Issue by sshine** [Athas/EggsML#115]
- [x] For Python 3 mangler pakken `lxml`. Man kan installere den med `pip3.6 install lxml` hvis man har rettigheder til at lægge den i /usr/local. Ellers skal den måske lægges et andet sted.

        <concieggs> hooks/01runcmd: /eggsml/concieggs/cmds/billedmem: Traceback (most recent call last):
        <concieggs> hooks/01runcmd: /eggsml/concieggs/cmds/billedmem:   File "/eggsml/concieggs/cmds/billedmem", line 15, in <module>
        <concieggs> hooks/01runcmd: /eggsml/concieggs/cmds/billedmem:     from lxml import html
        <concieggs> hooks/01runcmd: /eggsml/concieggs/cmds/billedmem: ModuleNotFoundError: No module named 'lxml'

- [x] Concieggs-monaden er tilsyneladende også gået i stykker på grund af manglende pakker:

        <simon> margrethe skål! :<|>: margrethe kål!
        <concieggs> hooks/02runoperator:
        <concieggs> hooks/02runoperator: /eggsml/concieggs/eggspi/haskeggs/Concieggs/Monad.hs:9:8:
        <concieggs> hooks/02runoperator:     Could not find module ‘Data.List.Utils’
        <concieggs> hooks/02runoperator:     Use -v to see a list of the files searched for.
        <concieggs> hooks/02runoperator:
        <concieggs> hooks/02runoperator: /eggsml/concieggs/eggspi/haskeggs/Concieggs/Random.hs:26:18:
        <concieggs> hooks/02runoperator:     Could not find module ‘Control.Monad.Random’
        <concieggs> hooks/02runoperator:     Use -v to see a list of the files searched for.
        <concieggs> hooks/02runoperator:
        <concieggs> hooks/02runoperator: /eggsml/concieggs/eggspi/haskeggs/Concieggs/Random.hs:27:18:
        <concieggs> hooks/02runoperator:     Could not find module ‘Data.Random’
        <concieggs> hooks/02runoperator:     Perhaps you meant Data.Ratio (from base-4.8.2.0)
        <concieggs> hooks/02runoperator:     Use -v to see a list of the files searched for.
        <concieggs> hooks/02runoperator:
        <concieggs> hooks/02runoperator: /eggsml/concieggs/eggspi/haskeggs/Concieggs/Random.hs:28:18:
        <concieggs> hooks/02runoperator:     Could not find module ‘Data.Random.Extras’
        <concieggs> hooks/02runoperator:     Use -v to see a list of the files searched for.
        <concieggs> hooks/02runoperator:
        <concieggs> hooks/02runoperator: /eggsml/concieggs/eggspi/haskeggs/Concieggs/Random.hs:29:8:
        <concieggs> hooks/02runoperator:     Could not find module ‘Data.Random.Distribution.Uniform’
        <concieggs> hooks/02runoperator:     Use -v to see a list of the files searched for.
        <concieggs> hooks/02runoperator: "runoperator" unexpectedly returned exit value 1 at /eggsml/concieggs/hooks/channel_message/02runoperator line 21.

**Comment by Athas** [comment]
--user

-- 
\  Troels
/\ Henriksen
