### ISSUE TITLE
Forskellig opførsel afhængig af ugedag

### ISSUE THREAD

**Issue by nqpz** [athas/EggsML#134]
concieggs skal glæde sig mere og mere jo tættere på weekenden vi kommer.

Om mandagen skal concieggs brokke sig og måske lade være med at køre nogle af kommandoerne.

Det kan passende aktiveres med `concieggs: vær på arbejde`. Se også #124.

concieggs skal også glæde sig til fredag efter arbejde, for da er der drinksaften med kollegaerne.

**Comment by sshine** [comment]
Alternativt `vær lønslave`.

**Comment by nqpz** [comment]
Hov! Der er mærkelige kodningsproblemer! Noget med UTF-8! Uha!

**Comment by Sword-Smith** [comment]
Er denne her lukket med `lønslave`-filteret?

**Comment by nqpz** [comment]
Det er uklart, men du må godt lukke den hvis du har lyst.

**Comment by Sword-Smith** [comment]
Lukket med 388ab8c13ca61066047175a94f2de13116b6a468, med mindre @sshine er uenig.
