### ISSUE TITLE
Hold Perl-moduler på serveren opdateret

### ISSUE THREAD

**Issue by sshine** [athas/EggsML#139]
I ny og næ sker det at Perl-installationen går i ged. Nogle gange er det fordi concieggs ikke kan finde Perlbrew og andre gange er der kommet en opdatering til Perl som gør at alle modulerne som er installeret ligger i en anden mappe end den som den nyere version af Perl bruger. (Der er sikkert også andre grunde.)

Man burde relativt nemt kunne scanne alle filer i concieggs-mappen igennem for Perl `use ...` og installere de moduler som skal installeres. Alternativt kunne man også liste modulerne et sted og have en hook som beder én vedligeholde denne modulliste. Måske findes der endda en standardiseret måde at have modullisten på.

**Comment by nqpz** [comment]
Hvad https://metacpan.org/pod/cpanfile

**Comment by Eckankar** [comment]
Det der nogle gange giver problemer er ikke at modulerne ikke er opdateret, men at jeg har sat perlbrew-perl som default med "perlbrew switch". https://perlbrew.pl/

Dvs, den bruger også perlbrew perl som default i scripts der beder om at blive kørt med perl, men som ikke er fra concieggs selv. 

Hvis der er et script (fx sloccount) som er installeret via systemet, men man prøver at køre det via perlbrew (hvilket man gør ved at køre det med `perl <script>` eller `#!/usr/bin/env perl` som shebang i det nuværende setup), så mangler der som regel nogle pakker.

Vi kunne evt. lave et script vi kan sætte som shebang i concieggs hvis det er, som bruger den passende version ud fra perlbrew. Det skal dog i givet fald være robust ift. brug i udviklingskontekst hvor stierne ikke er de samme.

**Comment by Eckankar** [comment]
Ift. cpanfile kan man kigge på hvad https://github.com/dikurevy/RevyTeX gør.

**Comment by sshine** [comment]
Idet Perl er dynamisk typet kan alle køretidsfejl betragtes som features.
