### ISSUE TITLE
Til "slåskamp" bør enten marvel_character eller $hyps være italic istedet for upper case

### ISSUE THREAD

**Issue by ericqzou** [athas/EggsML#147]
For folk som mig der kender ikke sygt meget til marvel verden er det svært at relatere mig til sætningen når både chars og hyponmyer er piped til toupper. Det vil være dejligt hvis den ene erlavet til italic, fx.

**Comment by athas** [comment]
Det kan IRC ikke.

**Comment by nqpz** [comment]
Der er mange andre muligheder:

- `*ord*`
- `*ORD*`
- `_ord_`
- `_ORD_`

**Comment by nqpz** [comment]
Eric har ikke gjort noget ved det, og vi andre er ligeglade, så jeg lukker sagen.
