### ISSUE TITLE
concieggs holder ikke sin kæft når man beder den om det!

### ISSUE THREAD

**Issue by sshine** [Athas/EggsML#18]
18:47:43 < concieggs:#diku> somesome, her på dansk:                  Skub n   -> skub n
18:48:06 < sshine:#diku> concieggs, hold nu din kæft!!!
18:48:07 < concieggs:#diku> OK!  Jeg skal nok tie stille (indtil i dag klokken 19:48).
18:48:46 < somesome:#diku> nte er defineret i en where
18:49:13 < sshine:#diku> foo (PUSH n) = push n
18:49:14 < concieggs:#diku> sshine, her på dansk: foo (Skub n) = skub n

**Comment by Athas** [comment]
Jeg tror det her er blevet rettet.
