### ISSUE TITLE
eggsml.dk viser ikke rigtigt antal frokost deltagere

### ISSUE THREAD

**Issue by nwillems** [Athas/EggsML#19]
I dag da jeg besøgte eggsml.dk var der en fej lpå siden :-(
```Der er 0 tilmeldt til Eggs i dag klokken 12:00: . Der skal tilberedes 1 eggs. ```

Der er tilmeldt 4 og der skal laves 2 eggs.
Det er ikke særligt blåt, øv bøv.

**Comment by Athas** [comment]
Det virker sikkert nu.
