### ISSUE TITLE
concieggs' bidrag til debatten skal styres vha. en charme-variabel.

### ISSUE THREAD

**Issue by MikkelStorgaard** [Athas/EggsML#23]
Der er mange steder i koden, hvor concieggs' aktive deltagelse er afgjort ved en maybeGood <tal>-kommando.
Jeg synes det kunne være smart, hvis det var maybeGood charmen.
Så kunne man bare skrue op og ned for concieggs' kækhed ved kommandoerne 
"concieggs: skru (op|ned) for charmen"

**Comment by MikkelStorgaard** [comment]
Opdatering på dette.

Selve charmefunktionen er nu implementeret, og ligger i hhv.
cmds/skru, og eggspi/ checkCharmen setCharmen ppCharmen

Nu skal det bare implementeres. 
Jeg foreslår man grepper på maybeGood og går i gang

**Comment by Athas** [comment]
Det sker nu.
