### ISSUE TITLE
Concieggs er ikke længere høflig nok

### ISSUE THREAD

**Issue by Athas** [Athas/EggsML#24]
I gamle dage kunne concieggs være spydig og fornærmende, men det skete altid med en vis højde i sproget.  Vi må tilbage til disse dage, i hvert fald for den mest centrale funktionalitet.

**Comment by nqpz** [comment]
On 2015-01-03 04:50:28, Troels Henriksen wrote:
> I gamle dage kunne concieggs være spydig og fornærmende, men det skete altid med en vis højde i sproget.  Vi må tilbage til disse dage, i hvert fald for den mest centrale funktionalitet.

Kan du give et eksempel?

**Comment by Athas** [comment]
`tror`, `nyemem`.

-- 
\  Troels
/\ Henriksen
