### ISSUE TITLE
Jeg skal selv omregne valuta i hovedet, når jeg bruger indkøb!

### ISSUE THREAD

**Issue by MikkelStorgaard** [athas/EggsML#25]
Hvorfor kn jeg ikke skrive "conciegss: indkøb 10 usd" ?
Det vil stor-globalisere EggsML

**Comment by Athas** [comment]
Du trænger alligevel til at træne din færdighedsregning!

Hvordan vil du adskille brugernavne og valutaer i notationen for indkøb?

**Comment by nqpz** [comment]
Ingen bruger den kommando længere, så nu lukker jeg sagen.
