### ISSUE TITLE
Concieggs skal kunne levere vejrudsigter

### ISSUE THREAD

**Issue by Sword-Smith** [Athas/EggsML#29]
openweathermap.org, der bruger som API kan også levere vejrudsigter. Dem skal brugerne på IRC-kanalerne have adgang til!

**Comment by Sword-Smith** [comment]
Man skal kunne spørge concieggs, om man skal medbringe regntøj i dag. Evt. med ens position som argument.

**Comment by Sword-Smith** [comment]
Meget minimal og grim vejrudsigt er nu implementeret. I må meget gerne forbedre den, hvis I vil. Open Weather Map har en API, der kan forudsige vejret med en tidsopløsning på tre timer. Den bør bruges for vejrudsigter for indeværende dag samt evt. for den følgende dag. vejrudsigt-funktionen er ikke deterministisk, da der vist nok er flere vejrudsigter tilgængelige, og da deres orden ikke er ens altid (tror jeg nok). Derfor kan man få to forskellige vejrudsigter, hvis man spørger to gange kort tid efter hinanden.

**Comment by Sword-Smith** [comment]
Med disse to informationer, kan man programmere en funktion, hvor concieggs kan svare på, om man bør tage en jakke på eller ej. Optimalt bør det kombineres med en vejrudsigt for de næste x timer, hvor x er et argument til funktionen. Er der noget tidspunkt inden for disse x timer, hvor man skal bruge en jakke, så skal concieggs svare "ja".
http://www.city-data.com/forum/weather/1988246-what-temperature-do-you-start-needing.html
http://en.wikipedia.org/wiki/File:Wind_chill.png

**Comment by MikkelStorgaard** [comment]
Er det her ikke fikset?

**Comment by nqpz** [comment]
Jo.
