### ISSUE TITLE
`base64`-programmet på Troels' OpenBSD giver dårlig uddata

### ISSUE THREAD

**Issue by nqpz** [Athas/EggsML#30]
På hans OpenBSD giver kørslen

    echo -n 'test' | base64 | hexdump

uddataen

    0000000    4764    7a56    4164    3d3d    0a0d                        
    000000a

mens samme kommando på min Debian giver uddataen

    0000000 4764 7a56 4164 3d3d 000a               
    0000009

Forskellen er at `0a0d` ikke er `000a`.  Jeg er ligeglad, men når jeg kører kommandoen

    echo "$(echo -n 'test' | base64)MERE"

vil jeg naturligvis gerne have uddataen

    dGVzdA==MERE

hvilket jeg da også får på min Debian, men på Troels' OpenBSD får jeg i stedet uddataen

    MEREdA==

altså hvor `0a0d` fungerer som en kontrolkode i både sh, dash og bash der får konsollen til at tro at den skal spole tilbage til begyndelsen af tekstfølgen i stedet for bare at skrive videre.

Jeg tror problemet er at `base64`-programmet slutter med `\n\r` i stedet for `\r\n`.  Er det fordi det er en underlig `base64`-udgave som Troels har installeret, eller tror I det er en reel bug?

Se forresten mit fiks i 54148226c614ea93730b925197da53c46e0c1205.

**Comment by concieggs** [comment]
"Niels G. W. Serup" <notifications@github.com> writes:

> På hans OpenBSD giver kørslen

OpenBSD er ligesom en hund - det kan fornemme hvis du ikke kan lide det,
og nægter så at være lydig.

> Jeg tror problemet er at `base64`-programmet slutter med `\n\r` i
> stedet for `\r\n`.  Er det fordi det er en underlig `base64`-udgave
> som Troels har installeret, eller tror I det er en reel bug?

Det er en underlig udgave.  base64 er ikke en del af OpenBSD, så det er
en eller anden pakke.  Forfatteren har skrevet koden med litterær
programmering, så det er nok nemt at finde fejlen:
https://www.fourmilab.ch/webtools/base64/base64.pdf

> Se forresten mit fiks i 54148226c614ea93730b925197da53c46e0c1205.

Du kan bare bruge gbase64.

-- 
\  Troels
/\ Henriksen

**Comment by concieggs** [comment]
"Niels G. W. Serup" <notifications@github.com> writes:

> Jeg tror problemet er at `base64`-programmet slutter med `\n\r` i
> stedet for `\r\n`.  Er det fordi det er en underlig `base64`-udgave
> som Troels har installeret, eller tror I det er en reel bug?

Du er forresten dum, tror jeg - base64 udskriver \r\n, men hexdump viser
byte-par i omvendt rækkefølge af hvad du forventer.

-- 
\  Troels
/\ Henriksen

**Comment by nqpz** [comment]
On 2015-05-21 11:48:54, Concieggs Nippenauer wrote:
> "Niels G. W. Serup" <notifications@github.com> writes:
> 
> > Jeg tror problemet er at `base64`-programmet slutter med `\n\r` i
> > stedet for `\r\n`.  Er det fordi det er en underlig `base64`-udgave
> > som Troels har installeret, eller tror I det er en reel bug?
> 
> Du er forresten dum, tror jeg - base64 udskriver \r\n, men hexdump viser
> byte-par i omvendt rækkefølge af hvad du forventer.

Øv!

Men er det virkeligt normalt at et shellprogram reagerer på \r\n ved at
gå tilbage til starten af linjen uden at starte en ny linje?

**Comment by Athas** [comment]
"Niels G. W. Serup" <notifications@github.com> writes:

> On 2015-05-21 11:48:54, Concieggs Nippenauer wrote:
>> "Niels G. W. Serup" <notifications@github.com> writes:
>> 
>> > Jeg tror problemet er at `base64`-programmet slutter med `\n\r` i
>> > stedet for `\r\n`.  Er det fordi det er en underlig `base64`-udgave
>> > som Troels har installeret, eller tror I det er en reel bug?
>> 
>> Du er forresten dum, tror jeg - base64 udskriver \r\n, men hexdump viser
>> byte-par i omvendt rækkefølge af hvad du forventer.
>
> Øv!
>
> Men er det virkeligt normalt at et shellprogram reagerer på \r\n ved at
> gå tilbage til starten af linjen uden at starte en ny linje?

Nej, men det er så vidt jeg kan se heller ikke hvad der sker - det er
bare sådan det ser ud, fordi \r ikke bliver fjernet.
