### ISSUE TITLE
Skal man kunne tilmelde sig frokoster via spindel?

### ISSUE THREAD

**Issue by Sword-Smith** [athas/EggsML#31]
Hjemmesiden kunne indholde en formular til at tilmelde sig frokost. Man skulle være indviet med et navn for at kunne tilmelde sig frokosten, og selve tilmeldingen kunne foregå gennem en ny bot på #Eggsml. I spindelformularen skal man så skrive det navn, man er indviet med og man er så med til næste frokost. I første omgang skal man ikke kunne oprette nye frokoster, men kun tilmelde sig eksisterende.

**Comment by svip** [comment]
Vi har slamkodet en masse.  Men nu er vi løbet ind i et rettighedsproblem.  Troels er dum.

**Comment by Sword-Smith** [comment]
En evt. løsning bør, så vidt jeg kan se, placeres i eggslib/concieggs_vm.py i funktionen eggsml_tilmeld(user). Det burde være tilstrækkeligt at redigere denne funktion og så af-kommentere nogle emballage-funktioner eggslib/eggsml_page.py. Den foreslåede løsning er en IRC-bot, der opfører sig lidt som "hej_fra_github".

**Comment by nqpz** [comment]
Det her er irrelevant nu hvor frokostklubben er død.
