### ISSUE TITLE
concieggs' humør skal afhænge af hvor fuld månen er

### ISSUE THREAD

**Issue by nqpz** [Athas/EggsML#35]
Vi mangler astrologi en masse på IRC!  Mere stjernelæsning og hurlumhej-digtning!  TIDEN ER KOMMET.

**Comment by Athas** [comment]
Stjernerne står rigtigt.

Mere Lovecraft i EggsML!

-- 
\  Troels
/\ Henriksen

**Comment by nqpz** [comment]
https://www.timeanddate.com/moon/phases/denmark/copenhagen

**Comment by Athas** [comment]
concieggs skal skifte til 'varulv'-væremåde når månen er fuld.  Denne
skal være en variant af 'bjørn'.

-- 
\  Troels
/\ Henriksen

**Comment by nqpz** [comment]
Nogen gør noget med cd891543361f6c9823d593c1bdd2d3d7b85ab7ed.

**Comment by sshine** [comment]
@Athas: Ville det ikke spille meget godt sammen med tidsbestemte kroge?

**Comment by nqpz** [comment]
Der er en varulv-filter nu.  Det må være nok til at lukke issue.
