### ISSUE TITLE
Høj prioritet: Lav et slack interface så man kan være webscale

### ISSUE THREAD

**Issue by NinnOgTonic** [Athas/EggsML#37]

**Comment by sshine** [comment]
Er der overhovedet nogen som bruger Slack her?

**Comment by nqpz** [comment]
On Thu, 17 Nov 2016 04:56:45 -0800, Simon Shine wrote:
> Er der overhovedet nogen som bruger Slack her?

Jeg tror at du når et større publikum ved at lave en rå
netcat-grænseflade.

**Comment by poizan42** [comment]
Hvad, bruger i ikke netcat til irc?
