### ISSUE TITLE
say er i stykker

### ISSUE THREAD

**Issue by Eckankar** [Athas/EggsML#38]
Den udelader mellemrum mellem argumenterne.

**Comment by Eckankar** [comment]
Så, nu virker den korrekt.

**Comment by Athas** [comment]
Sebastian Paaske Tørholm <notifications@github.com> writes:

> Så, nu virker den korrekt.

Jeg kunne bedre lide den hurtige udgave.

-- 
\  Troels
/\ Henriksen

**Comment by Eckankar** [comment]
Så må jeg hellere sætte dig på opgaven, så concieggs kan forblive web-scale.
