### ISSUE TITLE
Flere tilstandsbaserede spil i concieggs

### ISSUE THREAD

**Issue by nqpz** [athas/EggsML#40]
Lige nu har concieggs den skægge kommando `commitleg`, og iiih hvor kan man få mange timer til at gå med den.

Men der mangler flere sådanne spil som kræver flertrinshandlinger og ikke bare er `concieggs: noget, og så forresten ikke mere`.

Man kan evt. bruge det udmærkede sprog `rash` til at skrive disse tilstandsbaserede spil.  Det understøtter at man kan køre kommandoen flere gange efter hinanden, og at den opfører sig forskelligt hver gang, uden at det er et rod at kode og uden at der skal køre en baggrundsproces.

Bare kom i gang!  Jeg foreslår:
- <del>Jeopardy</del> (se 3a9121b96cc30271eb38bc6e6768f8c4ca708da6)
- ELIZA
- Banko?

Der er i hvert fald rigeligt med muligheder.

**Comment by MikkelStorgaard** [comment]
Man kan også putte en musikquiz op

**Comment by Eckankar** [comment]
Filmquiz: ee68a7daac7d70a72ab65acde7153a37d0adee1d

**Comment by nqpz** [comment]
Jeg lukker altså lige denne meta-sag.
