### ISSUE TITLE
Mere action og mindre \x01ACTION

### ISSUE THREAD

**Issue by poizan42** [Athas/EggsML#44]
Det ser fjollet ud, kan vi fikse det?

**Comment by Eckankar** [comment]
Det virker fint for mig. Hvad tænker du der er galt?

**Comment by poizan42** [comment]
Jeg har ikke tjekket nærmere hvad den sender, men xchat viser "\x01ACTION ... action tekst" som en almindelig besked når concieggs prøver at lave en action. Den må indkode det på en ikke-defacto-standard-følgende-måde.

**Comment by poizan42** [comment]
Sådan her f.eks.: http://imgur.com/aKWKANv

**Comment by poizan42** [comment]
Jeg tror jeg lurede den nu. En action besked skal både starte og slutte med \x01. concieggs action beskeder starter kun med \x01
