### ISSUE TITLE
Concieggs burde have adblocker-blocker-blocker

### ISSUE THREAD

**Issue by poizan42** [Athas/EggsML#47]
Der burde ske noget når man linker til en side som politiken med adblocker-blocker. Den kunne evt. sige noget i stil med:

> <bruger> Giv din adblocker-blocker en pause! Adblockere er en forudsætning for, at vores spindel-brugere hver dag kan betragte det ypperste indenfor journalistik og begavet underholdning.

**Comment by nqpz** [comment]
Sådanne kontroversielle udgydelser er kun i orden hvis der også er nogen modsatrettede holdninger til at balancere holdningsspektrummet, synes jeg.
Det er vigtigt at concieggs har en inkonsistent personlighed.

**Comment by sshine** [comment]
@poizan42: Er der en liste over sider som bruger adblocker-blockers?

**Comment by poizan42** [comment]
Tror jeg ikke, men vi kan altid tilføje dem som vi finder dem. Svarede jeg foreslog var selvfølgelig specifikt modelleret efter politiken.dk

**Comment by sshine** [comment]
Som den er lavet nu, kunne den godt blive irriterende hvis nogen linker til mange pol.dk-artikler, men på den anden side, er mange links til pol.dk-artikler jo irriterende i sig selv.

**Comment by poizan42** [comment]
Lukker du bare mit issue? :(

**Comment by sshine** [comment]
Du må gerne genåbne det, hvis du vil tilføje noget til adblocker-blocker-blockeren, men som udgangspunkt har Concieggs nu sådan en. :)

**Comment by poizan42** [comment]
Skal jeg ikke sige LGTM eller den danske udgave SFUFM eller sådan noget?

SFUFM

Nu må du godt lukke den

**Comment by svip** [comment]
Bør man ikke bare bruge NoScript eller µMatrix i stedet?  Så vises der ingen reklamer, men heller ingen adblocker-blocker.
