### ISSUE TITLE
Filtre er ligesom LP'er, men der er intet LP-filter!

### ISSUE THREAD

**Issue by sshine** [Athas/EggsML#54]
Antag ikke at bogstaver i hyperlinks skal gøres store.

**Comment by Athas** [comment]
Simon Shine <notifications@github.com> writes:

> Antag ikke at bogstaver i hyperlinks skal gøres store.

Du har min tilladelse til at fikse det.

-- 
\  Troels
/\ Henriksen

**Comment by nqpz** [comment]
On Thu, 06 Oct 2016 03:42:39 -0700, Troels Henriksen wrote:
> Simon Shine <notifications@github.com> writes:
> 
> > Antag ikke at bogstaver i hyperlinks skal gøres store.
> 
> Du har min tilladelse til at fikse det.

Jeg er lidt skeptisk, men jeg vil gerne have mere Emacs Lisp i
concieggs, så fiks det bare.

**Comment by sshine** [comment]
> Jeg er lidt skeptisk, men jeg vil gerne have mere Emacs Lisp i concieggs, så fiks det bare.

Jeg forstår ikke, hvad du mener. Capslock-filteret er kodet i Haskell. Siger du, jeg skal kode det om i Emacs Lisp?

**Comment by nqpz** [comment]
On Thu, 06 Oct 2016 05:05:48 -0700, Simon Shine wrote:
> > Jeg er lidt skeptisk, men jeg vil gerne have mere Emacs Lisp i
> > concieggs, så fiks det bare.
> 
> Jeg forstår ikke, hvad du mener. Capslock-filteret er kodet i
> Haskell. Siger du, jeg skal kode det om i Emacs Lisp?

Hov, jeg troede at du mente grel-filteret.  Den på
https://github.com/Athas/EggsML/blob/master/concieggs/filters/grel som
du også gerne må fikse.

**Comment by Eckankar** [comment]
Jeg er uenig i, at det bør fikses. Pointen er jo, at concieggs bare slår capslock til når han skriver adresser.

**Comment by Eckankar** [comment]
Man kan jo heller ikke bruge URL'er når concieggs er bjørn, oversat til andre sprog, etc.

Det er en del af charmen.

**Comment by nqpz** [comment]
On Thu, 06 Oct 2016 06:33:43 -0700, Sebastian Paaske Tørholm wrote:
> Man kan jo heller ikke bruge URL'er når concieggs er bjørn, oversat
> til andre sprog, etc.
> 
> Det er en del af charmen.

Dette er en god pointe.  Men det kunne stadig være rart at slå
speciel URL-håndtering til og fra.

**Comment by sshine** [comment]
@Eckankar: Ok, capslock-filteret transformerer trods alt bare URL'er. Grel-filteret destruerer information.

@nqpz: Det lyder svært at lave særlig URL-håndtering på tværs af filtre.

**Comment by nqpz** [comment]
On Thu, 06 Oct 2016 06:38:00 -0700, Simon Shine wrote:
> @nqpz: Det lyder svært at lave særlig URL-håndtering på tværs af filtre.

Det er en god udfordring.  Man kan gemme tilstanden i
$CONCIEGGS_DIR/store og ændre på runcmd.

**Comment by Eckankar** [comment]
@sshine 
* "bjørn", "nedern", "tavs" destruerer hele beskeden
* "json" har en 10% chance for at destruere hele beskeden.
* "flad" desturerer alt andet end ordlængder.
* "poptøz", "ordblin", "gangsta", "jysk", ... kan korrumpere dele af beskeden.
* Oversættelser kan fucke URL'er jævnt meget op, og omarrangere sætningsstrukturen.

Hvorfor skal URL'er behandles specielt i disse tilfælde? Filtrene korrumperer som regel data, ja; det er en del af charmen.

**Comment by Athas** [comment]
Sebastian Paaske Tørholm <notifications@github.com> writes:

> Filtrene korrumperer som regel data, ja; det er en del af charmen.

Simon, det Sebastian siger, er at concieggs-filtre er lidt ligesom LP'er.

-- 
\  Troels
/\ Henriksen

**Comment by sshine** [comment]
Jeg kan godt se hvordan det at oprette issues som overspringshandling på arbejdet har den uheldige følgevirkning at jeg tror, jeg skal fikse ting. Jeg vil i stedet lave et LP-filter som indlægger tilfældige skratte-ordlyde og med en vis sandsynlighed enten gentager en del af det, der bliver sagt, eller lader pick-up'en ryge helt af.

**Comment by Eckankar** [comment]
Blot få dage efter du foreslog det filter, så kom følgende XKCD:

![Record Scratch](http://imgs.xkcd.com/comics/record_scratch.png)

Tilfælde? Næppe.

**Comment by nqpz** [comment]
Hallooo, GitHuuuuub, jeg skrev "Lukker #54".
