### ISSUE TITLE
Udvid perleggs-biblioteket med EggsML::EggsPI

### ISSUE THREAD

**Issue by sshine** [athas/EggsML#62]
For eksempel

```
use EggsML::EggsPI qw(isKing isInBadStanding);
```

**Comment by Eckankar** [comment]
Jeg foretrækker:

```
use EggsML::EggsPI::Boolean qw/isKing isInBadStanding/;
use EggsML::EggsPI qw/randomName/;
```

Jeg vil gerne kigge på at lave noget smart.

**Comment by Eckankar** [comment]
@sshine Hvad tænker du om det udkast jeg er kommet med. Savner du noget i dét?

**Comment by sshine** [comment]
@Eckankar: Jeg kan godt lide det. Jeg skal nok lige prøve det, før jeg finder nogen mangler.

**Comment by Eckankar** [comment]
Der er muligvis nogle encoding issues. Det skal lige checkes.
