### ISSUE TITLE
Lav et pruttefilter

### ISSUE THREAD

**Issue by nqpz** [Athas/EggsML#66]
Filteret skal indsætte pruttelyde visse steder.  Det er ikke for sjov!

**Comment by nqpz** [comment]
Der skal også være indskudte linjer såsom:

```
/me lægger en kæmpe lort.
/me har ekstremt dårlig mave.
/me glemmer at lukke døren til toilettet.
```

**Comment by sshine** [comment]
@nqpz: Hvad mangler filteret i øvrigt? @Athas [antydede](https://github.com/Athas/EggsML/commit/dddbb2d4b083150003c7cd2dca6518f99fa8b81a#commitcomment-19574282) at høfligheden er røget lidt.

**Comment by nqpz** [comment]
On Wed, 02 Nov 2016 08:39:14 -0700, Simon Shine wrote:
> @nqpz: Hvad mangler filteret i øvrigt? @Athas [antydede](https://github.com/Athas/EggsML/commit/dddbb2d4b083150003c7cd2dca6518f99fa8b81a#commitcomment-19574282) at høfligheden er røget lidt.

Man kan godt lave høflige prutter ved at undskylde efter hver prut.

**Comment by sshine** [comment]
Concieggs' pruttefilter akkumulerer indtil videre luft uden mulighed for at aflaste det.

Det er en klar mangel, men kan betragtes som en separat problemstilling fra pruttefilteret selv.
