### ISSUE TITLE
Sprog der mangler

### ISSUE THREAD

**Issue by poizan42** [athas/EggsML#70]
Som @PhDuck sagde i #52 vi mangler en liste over sprog der mangler. Efter som der er jævnt mange mulige programmeringssprog tænker jeg vi måske skal prøve at lave noget hvor man kan stemme på dem.

Lad os starte med at samle en liste over hvilke sprog vi har lige nu:
- Perl (5 & 6)
- Python (2 & 3)
- sh (& bash)
- C
- Haskell
- Object Pascal
- Go
- SML
- Ruby
- RASH
- TCL
- Javascript (Node)
- Brainfuck
- PHP
- [Gotta Go Fast](https://github.com/Athas/EggsML/blob/master/concieggs/cmds/matematik) (Troels'es sprog fra AP for et par år siden)

**Comment by sshine** [comment]
Og her er en række sprog som mangler, som samtidigt er blevet foreslået:
* Java ( #52 )
* PHP ( #53 )

**Comment by poizan42** [comment]
Hov jeg kan ikke se nogen liste over sprog der mangler. Dette problem er ikke løst endnu.

**Comment by sshine** [comment]
Jeg glemte at tilføje, at hensigten med at lukke dette issue var, at jeg tænker, det ikke har bragt os tættere på en større repræsentation af programmeringssprog i robotten. Listen @PhDuck beskriver er ikke mulig, selvom vi lavede en stor liste af sprog som ikke var dækket, er det ikke endsbetydende med at der vil blive skrevet programmer, da der også er en arbejdsbyrde forbundet med at installere et miljø til afvikling af programmer i det gældende programmeringssprog.

Så synes jeg hellere, vi skal oprette issues som #52 eller #97.

Hvis du stadig gerne vil have en liste over sprog vi endnu ikke benytter, synes jeg du skal lave den.

**Comment by nqpz** [comment]
Jeg lukker lige denne mærkelige meta-sag.
