### ISSUE TITLE
Concieggs er blevet doven!

### ISSUE THREAD

**Issue by sshine** [Athas/EggsML#73]
Det kan ikke passe at concieggs skal gabe kort før frokost!

    11:35:42 < Nikkel> godmorgen!
    11:35:43 < concieggs> Nikkel: Gaaaab!

**Comment by nqpz** [comment]
On Fri, 04 Nov 2016 03:37:32 -0700, Simon Shine wrote:
> Det kan ikke passe at concieggs skal gabe kort før frokost!
> 
>     11:35:42 < Nikkel> godmorgen!
>     11:35:43 < concieggs> Nikkel: Gaaaab!

Jeg synes at det er okay at concieggs er et B-menneske.

**Comment by Eckankar** [comment]
B for Bot.
