### ISSUE TITLE
Juleniveau

### ISSUE THREAD

**Issue by sshine** [Athas/EggsML#74]
Indtil videre:
* 8e29934540ba2dc4d292105e9b75bfa378f95d73 (første commit)
* 8f311d6f6fcf871b0b0226c330b955e4737d1ba8
* 6a90af3a7415c64070578bc84c563d7496743f6f
* d66b396ee609fe4fa1564281883a97171935a1e2
* 379a9af85e2efccfaab9d7b225df628ea6234638

**Comment by sshine** [comment]
- `isChristmas` ekskluderer 23. november mens `christmasLevel` inkluderer denne dato.
- I stedet for en fast dato, så lad julen starte 1. adventssøndag. Find denne dato!

**Comment by Athas** [comment]
Venligst at skrive et C-program til at lave denne besværlige udregning.
concieggs er langsom nok allerede.

-- 
\  Troels
/\ Henriksen

**Comment by sshine** [comment]
@ericqzou: Nu da `isChristmas` og `christmasLevel` er kodet i C, kunne du gøre christmas level til en ikke-monoton funktion som tager højde for advent.

**Comment by sshine** [comment]
Jamen god jul!

**Comment by sshine** [comment]
Det ser ud til at juleniveauet kan og bør raffineres yderligere.

- [ ] Max ud juleaften.
