### ISSUE TITLE
Monogami

### ISSUE THREAD

**Issue by sshine** [Athas/EggsML#75]
Lige nu bliver man kærester med concieggs når man kysser hen.

Det bør nok være sådan at concieggs ikke vil kysse med andre end sin kæreste, og at man bliver kærester med concieggs ved at have bedre karma end den nuværende, eller være den nuværende regent, og spørge, `concieggs, skal vi være kærester?` for sådan foregår det jo.

Ydermere, bør `concieggs, elsker du <person>?` fungere.

Ydermere, bør `flaske` have en sandsynlighed for kun at pege på kæresten, og ellers en større sandsynlighed for at stoppe på kæresten.

- [x] `concieggs, elsker du <person>?`
- [ ] `concieggs, skal vi være kærester?`
- [x] `/me kysser concieggs` forbeholdt kæreste.
- [ ] Tilføj bias til `flaske`.

HILSEN SIMON

**Comment by nqpz** [comment]
On Fri, 25 Nov 2016 07:16:12 -0800, Simon Shine wrote:
> Lige nu bliver man kærester med concieggs når man kysser hen.
> 
> Det bør nok være sådan at concieggs ikke vil kysse med andre end sin
> kæreste, og at man bliver kærester med concieggs ved at have bedre
> karma end den nuværende, og spørge, `concieggs, skal vi være
> kærester?` for sådan foregår det jo.

Ja, lad os formalisere kærlighedens sprog.

Man skal også kunne unfriende concieggs i en periode fordi man er _SÅ_
over hen.
