### ISSUE TITLE
Meme-operator

### ISSUE THREAD

**Issue by Eckankar** [Athas/EggsML#78]
Lav en meme operator. Sådan at

```
Overskrift :meme: Underskrift
```

giver et meme á la ![Meme-eksempel](https://i.imgflip.com/1g2vmw.jpg)

Dvs, hvor venstresiden er i toppen af memet, og højresiden er i bunden af memet.

**Comment by nqpz** [comment]
On Fri, 16 Dec 2016 04:03:07 -0800, Sebastian Paaske Tørholm wrote:
> Lav en meme operator. Sådan at
> 
> ```
> Overskrift :meme: Underskrift
> ```
> 
> giver et meme á la ![Meme-eksempel](https://i.imgflip.com/1g2vmw.jpg)
> 
> Dvs, hvor venstresiden er i toppen af memet, og højresiden er i bunden af memet.

Operatoren kan bare kalde `eggspi/makeMeme`, så det burde ikke være så
svært.
