### ISSUE TITLE
sshine har commitadgang

### ISSUE THREAD

**Issue by svip** [Athas/EggsML#81]
Nogen!  Fratag manden denne adgang!  Han kan slet ikke finde ud af at styre det!

**Comment by svip** [comment]
Hvis han ikke kan fratages commitadgang, skal han have undervisning i at programmere.  Jeg kan anbefale DIKU.

**Comment by sshine** [comment]
Jeg er enig i mærkatet "Katastrofe", men du er nødt til at uddybe problematikken hvis den skal afhjælpes. Er det fordi jeg koder Perl?

**Comment by svip** [comment]
Nej, det er fordi du laver commits som denne: 9715b326b

Jeg nævnte problematikken for 27 dage siden, på committet!  Men intet blev der gjort!

**Comment by svip** [comment]
Sågar @Eckankar er trist!  Og er han normalt trist?!

**Comment by svip** [comment]
Svaret er nej, fordi han har en fyldepen.  Faktisk flere.
