### ISSUE TITLE
Koen er blevet kværket. :(

### ISSUE THREAD

**Issue by sshine** [Athas/EggsML#82]
15:08:31 <sshine> concieggs, ko
    15:09:50 <concieggs> ________________________
    15:09:53 <concieggs> (\ | / (__))
    15:09:55 <concieggs> ( '\ ------ (Oo))
    15:09:56 <concieggs> (|| (__))
    15:09:58 <concieggs> (|| || W-- \ | /)
    15:09:59 <concieggs> (\ | /)
    15:10:01 <concieggs> ------------------------
    15:10:02 <concieggs> o ^ __ ^
    15:10:03 <concieggs> o (xx) \ _______
    15:10:05 <concieggs> \ / \ (__) \)
    15:10:06 <concieggs> U ||  ---- W |
    15:10:07 <concieggs> ||  ||

**Comment by Eckankar** [comment]
Og det er ikke bare filtre?

**Comment by sshine** [comment]
Nå jo, det er det.
