### ISSUE TITLE
Oversæt Kleenex-kode i baggrunden

### ISSUE THREAD

**Issue by sshine** [Athas/EggsML#83]
Det tager cirka ti minutter at oversætte `makeDanish.kex`.

I mellemtiden bør concieggs ikke være ude af drift.

**Comment by sshine** [comment]
Dette er i stedet fikset af @Eckankar i 4d63f398acb841bc4297f092ba88e1a92d55a5d3.

**Comment by Eckankar** [comment]
Jeg ved ikke om det hjalp synderligt. :) Min idé var dog, at dele det op i flere faser, så hver fase er simplere. Så burde oversættelsen gå hurtigere, hvis der ikke er for meget ambiguity.
