### ISSUE TITLE
Athas lavede en ændring på et udenlandsk sprog

### ISSUE THREAD

**Issue by svip** [Athas/EggsML#84]
Ændringsbeskeden på 4a739abfd0dbed40c0fe9c0a27dd6601e52b89d9 var på et ikke-dansk sprog.  Jeg forstod ikke beskeden.  Jeg efterlyser en oversættelse.

Desuden vil jeg også frabede folk fra at bruge ikke-danske sprog når de foretager kodeændringer og lægger dem op.

Jeg har tilføjet @Athas til opgaven, da det var ham der foretog ændringen.

På forhånd tak.

**Comment by nqpz** [comment]
On Sun, 29 Jan 2017 13:43:34 -0800, svip wrote:
> Ændringsbeskeden på 4a739abfd0dbed40c0fe9c0a27dd6601e52b89d9 var på et ikke-dansk sprog.  Jeg forstod ikke beskeden.  Jeg efterlyser en oversættelse.
> 
> Desuden vil jeg også frabede folk fra at bruge ikke-danske sprog når de foretager kodeændringer og lægger dem op.
> 
> Jeg har tilføjet @Athas til opgaven, da det var ham der foretog ændringen.
> 
> På forhånd tak.

Jeg anbefaler desuden en 'git push -f'.

**Comment by svip** [comment]
Jeg håber at nogen kan komme med en oversættelse!

**Comment by sshine** [comment]
> frabede folk fra at bruge ikke-danske sprog

Hvilke danske sprog foretrækker du at vi afgrænser os til?

Jeg fuldbyrder gerne mine ændringer med lidt jysk.

**Comment by kfl** [comment]
Men beskeden er jo på Jysk? Prøv selv at læse den højt.

Jeg forstår ingenting.

**Comment by Athas** [comment]
Problemet løst af Ken.

**Comment by svip** [comment]
Jeg vil ikke anse problemet som løst, men snarer at det ikke *kan* løses.

@sshine Opret en separat sag om hvilket danske mål der vil være at foretrække.
