### ISSUE TITLE
Tag højde for inflationen i samfundet

### ISSUE THREAD

**Issue by dybber** [Athas/EggsML#9]
Det er for dårligt at folk der er lang tid om at indfri sin gæld får deres måltider billigere pga. inflation!

**Comment by Sword-Smith** [comment]
Niels: Concieggs kunne faktisk levere sine egne inflationstal baseret på udviklingen i den gennemsnitlige måltidspris. Den kunne evt. udjævnes, eller man kunne lave en lineær regression af den.

**Comment by nqpz** [comment]
EggsML er død, så jeg lukker denne sag.
