### ISSUE TITLE
PHP-væremåden er ikke skrevet i PHP!

### ISSUE THREAD

**Issue by sshine** [athas/EggsML#97]
[`filters/php`](https://github.com/Athas/EggsML/blob/master/concieggs/filters/php) er skrevet i Perl og ikke i PHP.

**Comment by svip** [comment]
Ja, Mikkel er manden til at redde os.

**Comment by MikkelStorgaard** [comment]
On Thu, Feb 22, 2018 at 11:55 AM, svip <notifications@github.com> wrote:

> Ja, Mikkel er manden til at redde os.
>

Fordi jeg ikke kan kode php?

**Comment by sshine** [comment]
> Fordi jeg ikke kan kode php?

Arh... Det tager kun [Y minutter](https://learnxinyminutes.com/docs/php/) at lære.

**Comment by MikkelStorgaard** [comment]
Den fre. 23. feb. 2018 12.44 skrev Simon Shine <notifications@github.com>:

> Fordi jeg ikke kan kode php?
>
> Arh... Det tager kun Y minutter <https://learnxinyminutes.com/docs/php/>
> at lære
>

Jamen der står kun hvordan jeg laver tal.der er intet afsnit om concieggs!

>

**Comment by nqpz** [comment]
Du kan lave et pull request på https://github.com/adambard/learnxinyminutes-docs

**Comment by sshine** [comment]
> der står kun hvordan jeg laver tal

Alt i computere er alligevel repræsenteret med binære tal!

Jeg tilføjer lige til referatet:

    17:03:58 <simon> concieggs, hægtekongen php
    17:03:59 <concieggs> Top 5 hægtere for php:
    17:03:59 <concieggs>   52 Nikkel
    17:03:59 <concieggs>   34 Sebbe
    17:04:00 <concieggs>   32 svip
    17:04:00 <concieggs>   20 Athas
    17:04:01 <concieggs>   10 ngws
    17:04:09 <Nikkel> hva

**Comment by sshine** [comment]
Det er meget sjovt, men hvad så.
