### ISSUE TITLE
Batterifunktion

### ISSUE THREAD

**Issue by sshine** [Athas/EggsML#99]
Når den moderne frokostklub er på farten, er det en fordel hvis frokostrobotten kan tages med. Ældre modeller kræver imidlertid vægstrøm. For at bevare status som en moderne enterprise, foreslås hermed en batterifunktion så concieggs kan slå nogle af sine mindre kritiske funktioner fra hvis den er lav på batteri.

Jeg foreslår hermed at en prototype udvikles før vi sætter egentlige batterier i.

**Comment by Athas** [comment]
Der er vist en UPS i det datacenter hvor concieggs er opstaldet.  Er det
ikke et batteri?

-- 
\  Troels
/\ Henriksen

**Comment by sshine** [comment]
Så sjovt er det heller ikke.
